server:
  port: 8082

spring:
  datasource:
    username: user
    password: user123
    url: jdbc:mysql://mysql-cart:3306/cartdb?useSSL=false&allowPublicKeyRetrieval=true
#for local
#spring.datasource.url=jdbc:mysql://localhost:3307/cartdb?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}